version: 0.2

proxy:
  logs: yes

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - pip3.9 install --target ./package requests-aws4auth opensearch-py inflect
      - cd package
      - zip -r ../LF1_deployment.zip .
      - zip -r ../LF2_deployment.zip .
      - cd ..
      - mv LF1.py lambda_function.py
      - zip LF1_deployment.zip lambda_function.py
      - mv lambda_function.py LF1.py
      - mv LF2.py lambda_function.py
      - zip LF2_deployment.zip lambda_function.py
      - mv lambda_function.py LF2.py
  post_build:
    commands:
      - aws lambda update-function-code --function-name index-photos --zip-file fileb://LF1_deployment.zip
      - aws lambda update-function-code --function-name search-photos --zip-file fileb://LF2_deployment.zip

artifacts:
  files:
    - LF1_deployment.zip
    - LF2_deployment.zip
    - appspec.yml
  name: lambdas
