version: 0.2

proxy:
  logs: yes

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - pip install requests-aws4auth opensearch-py inflect
      - ls
artifacts:
  files:
    - LF1.py
    - LF2.py
    - appspec.yml
  name: lambdas
